app = "slackline"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "slackline_data"
  destination = "/data"

[env]
  DATABASE_PATH = "/data/slackline.db"
  NODE_ENV = "production"
